location / {
    try_files $uri $uri/ /bitrix/urlrewrite.php$is_args$args;
}

location ~ \.php$ {
    fastcgi_pass   127.0.1.26:9000;
    fastcgi_index  index.php;
    include        fastcgi_params;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
}